### ISSUE TITLE
Populate --consumer-app-version from git commit when --auto-detect-version-properties is used.

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact_broker-client#100]
Currently, you must provide the -consumer-app-version as well as --auto-detect-version-properties

**Comment by TimothyJones** [comment]
This is a good idea! I think `--consumer-app-version` should override anything that was autodetected, though.

**Comment by TimothyJones** [comment]
^ Can we get this public? It's not a great experience as an outside interested party to see issues moved somewhere that we can't see them.
