### ISSUE TITLE
--auto-detect-version-properties fails on github PR builds

### ISSUE THREAD

**Issue by TimothyJones** [pact-foundation/pact_broker-client#102]
GitHub's checkout action checks out against a merge commit on a PR build. This is the ideal behaviour for a PR build, because generally you want to build and test what master would look like with the pull request merged. 

However, this means that the ruby standalone's `--auto-detect-version-properties` fails with:

```
PactBroker::Client::Error - Command `git rev-parse --abbrev-ref HEAD` didn't return anything that could be identified as the current branch.
```

This is because `git rev-parse --abbrev-ref HEAD` does not know what the branch is on a PR build, regardless of the depth of commits fetched from the repo. (The result of `git rev-parse --abbrev-ref HEAD` is `HEAD` here).

As far as I can see, I can't configure github actions to do different behaviour where we would get the branch name from this command (I can tell it not to make a merge commit, but if I do that then we only build the branch in isolation, without the result of the merge).
 
Are we able to get the ruby standalone to fall back on the CI environment variables if `git rev-parse --abbrev-ref HEAD` doesn't have the branch? (or if it already does this, do we need to add the github CI variable to the list?)

**Comment by omermorad** [comment]
Adding:
```
    env:
      GITHUB_BRANCH: ${{ github.ref }}
```

can solve it, but the pact broker-client needs to get the branch from external args

**Comment by TimothyJones** [comment]
My understanding is that will force the PR to build the branch, and not the merge commit. This isn't what you would want in a PR build, since having a PR build is for "would this pass if I merged it in to the main branch".

(push commits on branches work fine with `--auto-detect-version-properties`)

**Comment by YOU54F** [comment]
The list is here

https://github.com/pact-foundation/pact_broker-client/blob/2b8dac5fef42b8ab0b846892b444097bbd067fda/lib/pact_broker/client/git.rb#L28

what is the env var set in GH actions for the branch var (ill go check the docs)

**Comment by YOU54F** [comment]
GH Actions docs here for env vars https://docs.github.com/en/actions/learn-github-actions/environment-variables


GITHUB_BASE_REF | The name of the base ref or target branch of the pull request in a workflow run. This is only set when the event that triggers a workflow run is either pull_request or pull_request_target. For example, main.
-- | --
GITHUB_HEAD_REF | The head ref or source branch of the pull request in a workflow run. This property is only set when the event that triggers a workflow run is either pull_request or pull_request_target. For example, feature-branch-1.

**Comment by bethesque** [comment]
I think we'd want `GITHUB_HEAD_REF` (eg `feature-branch-1`). I'll add it to the list ahead of `GITHUB_REF` so it gets found first if it exists.

**Comment by bethesque** [comment]
https://github.com/pact-foundation/pact_broker-client/pull/103

**Comment by TimothyJones** [comment]
I'm not sure this is fixed - see https://github.com/pact-foundation/pact-js/runs/5562046358?check_suite_focus=true

**Comment by YOU54F** [comment]
That build is using 1.88.63 of pact-standalone, as packaged with the version of pact-node.

@mefellows released a new version of pact-node yesterday which is using 1.88.88 which contains this change

see this [PR](https://github.com/pact-foundation/pact-js/pull/839) and associated build run :)

**Comment by YOU54F** [comment]
Just got this failing on a Github actions PR build but passing on the commit build

<img width="1096" alt="Screenshot 2022-10-07 at 13 00 44" src="https://user-images.githubusercontent.com/19932401/194548313-757787d5-b5c3-4c05-b5c4-0c22a32f2669.png">


https://github.com/pactflow/actions/actions/runs/3204533080/jobs/5235946790#step:3:100

```
Digest: sha256:8587ff66eb15cf6febea893a6e6fd8ae05ff66020ff2dd06b1be66af96400d32
Status: Downloaded newer image for you54f/pact-cli:latest
PactBroker::Client::Error - Command `git rev-parse --abbrev-ref HEAD` didn't return anything that could be identified as the current branch.
```

passes on a branch commit

https://github.com/pactflow/actions/actions/runs/3204506236/jobs/5235884881#step:3:101

```
Created actions-consumer version 5104672ef757a840b53ab0b9aceab6d93180b115 with branch test_git_safe_dir_issue
Pact successfully published for actions-consumer version 5104672ef757a840b53ab0b9aceab6d93180b115 and provider actions-provider.
  View the published pact at https://testdemo.pactflow.io/pacts/provider/actions-provider/consumer/actions-consumer/version/5104672ef757a840b53ab0b9aceab6d93180b115
  Events detected: contract_published (pact content is the same as previous versions with tags  and no new tags were applied), contract_requiring_verification_published (pact content is the same as previous versions with tags  and no new tags were applied)
  Next steps:
    * Add Pact verification tests to the actions-provider build. See https://docs.pact.io/go/provider_verification
    * Configure separate actions-provider pact verification build and webhook to trigger it when the pact content changes. See https://docs.pact.io/go/webhooks
```

**Comment by YOU54F** [comment]
PR Env vars (failing)

https://github.com/pactflow/actions/actions/runs/3204626096/jobs/5236155608#step:3:11

```
GITHUB_WORKSPACE=/home/runner/work/actions/actions
GITHUB_PATH=/home/runner/work/_temp/_runner_file_commands/add_path_2fc16460-fa77-46e4-96fa-eb97ed664489
GITHUB_ACTION=__run
GITHUB_RUN_NUMBER=45
GITHUB_TRIGGERING_ACTOR=YOU54F
GITHUB_REF_TYPE=branch
GITHUB_ACTIONS=true
GITHUB_SHA=ca79d2c3f22e2ca40eddb29d72d7470c80adc39d
GITHUB_REF=refs/pull/[13](https://github.com/pactflow/actions/actions/runs/3204626096/jobs/5236155608#step:3:14)/merge
GITHUB_REF_PROTECTED=false
GITHUB_API_URL=https://api.github.com
GITHUB_STATE=/home/runner/work/_temp/_runner_file_commands/save_state_2fc[16](https://github.com/pactflow/actions/actions/runs/3204626096/jobs/5236155608#step:3:17)460-fa77-46e4-96fa-eb97ed664489
GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_2fc16460-fa77-46e4-96fa-eb97ed664489
GITHUB_EVENT_PATH=/home/runner/work/_temp/_github_workflow/event.json
GITHUB_EVENT_NAME=pull_request
GITHUB_RUN_ID=3[20](https://github.com/pactflow/actions/actions/runs/3204626096/jobs/5236155608#step:3:21)4626096
GITHUB_STEP_SUMMARY=/home/runner/work/_temp/_runner_file_commands/step_summary_2fc16460-fa77-46e4-96fa-eb97ed664489
GITHUB_ACTOR=YOU54F
GITHUB_RUN_ATTEMPT=1
GITHUB_GRAPHQL_URL=https://api.github.com//graphql
GITHUB_SERVER_URL=https://github.com/
GITHUB_REF_NAME=13/merge
GITHUB_JOB=publish-pact-files
GITHUB_REPOSITORY=pactflow/actions
GITHUB_RETENTION_DAYS=90
GITHUB_ACTION_REPOSITORY=
GITHUB_BASE_REF=main
GITHUB_REPOSITORY_OWNER=pactflow
GITHUB_HEAD_REF=test_git_safe_dir_issue
GITHUB_ACTION_REF=
GITHUB_WORKFLOW=Actions test
GITHUB_OUTPUT=/home/runner/work/_temp/_runner_file_commands/set_output_2fc16460-fa77-46e4-96fa-eb97ed664489
```

Commit Env Vars (Passing)

https://github.com/pactflow/actions/actions/runs/3204625735/jobs/5236154106#step:3:11

```
GITHUB_WORKSPACE=/home/runner/work/actions/actions
GITHUB_PATH=/home/runner/work/_temp/_runner_file_commands/add_path_fb81fbd9-0126-4ac9-b320-f774bc405f62
GITHUB_ACTION=__run
GITHUB_RUN_NUMBER=44
GITHUB_TRIGGERING_ACTOR=YOU54F
GITHUB_REF_TYPE=branch
GITHUB_ACTIONS=true
GITHUB_SHA=21ed6980e83da0728965ead2cb48df22387f2c60
GITHUB_REF=refs/heads/test_git_safe_dir_issue
GITHUB_REF_PROTECTED=false
GITHUB_API_URL=https://api.github.com
GITHUB_STATE=/home/runner/work/_temp/_runner_file_commands/save_state_fb81fbd9-0[12](https://github.com/pactflow/actions/actions/runs/3204625735/jobs/5236154106#step:3:13)6-4ac9-b3[20](https://github.com/pactflow/actions/actions/runs/3204625735/jobs/5236154106#step:3:21)-f774bc405f62
GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_fb81fbd9-0126-4ac9-b320-f774bc405f62
GITHUB_EVENT_PATH=/home/runner/work/_temp/_github_workflow/event.json
GITHUB_EVENT_NAME=push
GITHUB_RUN_ID=3204625735
GITHUB_STEP_SUMMARY=/home/runner/work/_temp/_runner_file_commands/step_summary_fb81fbd9-0126-4ac9-b320-f774bc405f62
GITHUB_ACTOR=YOU54F
GITHUB_RUN_ATTEMPT=1
GITHUB_GRAPHQL_URL=https://api.github.com//graphql
GITHUB_SERVER_URL=https://github.com
GITHUB_REF_NAME=test_git_safe_dir_issue
GITHUB_JOB=publish-pact-files
GITHUB_REPOSITORY=pactflow/actions
GITHUB_RETENTION_DAYS=90
GITHUB_ACTION_REPOSITORY=
GITHUB_BASE_REF=
GITHUB_REPOSITORY_OWNER=pactflow
GITHUB_HEAD_REF=
GITHUB_ACTION_REF=
GITHUB_WORKFLOW=Actions test
GITHUB_OUTPUT=/home/runner/work/_temp/_runner_file_commands/set_output_fb81fbd9-01[26](https://github.com/pactflow/actions/actions/runs/3204625735/jobs/5236154106#step:3:27)-4ac9-b[32](https://github.com/pactflow/actions/actions/runs/3204625735/jobs/5236154106#step:3:33)0-f774bc[40](https://github.com/pactflow/actions/actions/runs/3204625735/jobs/5236154106#step:3:41)5f62
```

**Comment by YOU54F** [comment]
Just added in some tests using those env vars, taken from the action runs and they all pass as expected

https://github.com/pact-foundation/pact_broker-client/compare/github_pull_req_refs?expand=1

https://github.com/pact-foundation/pact_broker-client/actions/runs/3205586872

**Comment by YOU54F** [comment]
I need to load the env var into the docker container, I feel silly 😂 but it's working and the tests weren't lying to me! 

https://github.com/pactflow/actions/commit/cf30be55588e4fb5924f44e18db98f916b82c9e5

assume we should be able to pull these in, automatically for the user.
