### ISSUE TITLE
Test on newer supported rubies, drop unsupported rubies.

### ISSUE THREAD

**Issue by trammel** [pact-foundation/pact_broker-client#111]
Ruby 2.6 is EOL and will no longer receive any updates, including security fixes. https://www.ruby-lang.org/en/downloads/branches/
Ruby 2.2 has been EOL for more than four years now.

3.1 is now stable & current, not experimental.

I understand 2.2 is required for https://github.com/pact-foundation/pact-ruby-standalone, but pact-standalone [is also not being maintained anymore](https://github.com/pact-foundation/pact-ruby-standalone/issues/70#issuecomment-967725063), as it's totally dependent on Travelling Ruby, which is unmaintained, and it's single ruby 2.4 release dropped support for x86-linux.

I've got a branch https://github.com/trammel/pact_broker-client/tree/chore/bump-ruby-versions which bumps the matrix of rubies to be tested to just supported versions, and the tests are passing fine.

**Comment by bethesque** [comment]
Thanks, please do submit the change as a PR.

The 2.2 build was running properly up until a few months ago, when we stopped being able to install things on it. Now we're moving to 2.4 for Travelling Ruby (many thanks!) we should add 2.4 into the matrix to make sure we don't commit anything backwards incompatible. 

I wouldn't say the pact-standalone is not being maintained any more, it's just not being improved. We do still have to keep it going in it's current form for all the users who are currently using a Pact library that depends on it (like you!)

**Comment by trammel** [comment]
> I wouldn't say the pact-standalone is not being maintained any more, it's just not being improved. We do still have to keep it going in its current form for all the users who are currently using a Pact library that depends on it (like you!)

You're right. I didn't really understand the ongoing relationship between the software when I wrote that.

**Comment by trammel** [comment]
> Thanks, please do submit the change as a PR.

Okay. I might have been a bit aggressive with dropping older rubies. :grin: 

https://github.com/pact-foundation/pact_broker-client/pull/112/files

**Comment by trammel** [comment]
The merge happened, but the git actions failed on master.

https://github.com/pact-foundation/pact_broker-client/runs/6619274266?check_suite_focus=true

I'm happy to close this issue if you're okay?

**Comment by YOU54F** [comment]
The GH actions look to fail to upload the Pacts to Pactflow as forks don't have access to the credentials.

Thanks for the change buddy
