### ISSUE TITLE
Add getting list of deployed/released versions for the specific pacticipant 

### ISSUE THREAD

**Issue by avramchik** [pact-foundation/pact_broker-client#115]
Pact cli has endpoing to get tagged versions (describe-version), but there's no filter for environments. It would be good to add endpoint to get pacticipant deployed/released versions for all/specific environment. We use it to verify newly incoming pact against older(deployed) version of code to satisfy can-i-deploy step

**Comment by bethesque** [comment]
I'm all for this feature, but have you investigated the use of the "contract published requiring verification" webhook for achieving this? That's what it is designed for. Blog post [here](https://docs.pact.io/blog/2021/10/11/contract-requiring-verification-published-webhook-event) and docs [here](https://docs.pact.io/pact_broker/webhooks#using-webhooks-with-the-contract_requiring_verification_published-event).

**Comment by bethesque** [comment]
What is the configured main branch of the provider? You can look at it in the HAL browser by going to /pacticipants/:name.

**Comment by avramchik** [comment]
Oh it's misconfigured for some reason. What a surprise. I tried it with another provider and got the right results. But I still have a question about the `providerVersionNumber`. Will I get all provider versions deployed on different environments (older than actual main)?

**Comment by bethesque** [comment]
Yes. You will get every provider version that is currently deployed or released. It will de-duplicate them though, so you'll only get one build per version, even if it's deployed in many places.
