### ISSUE TITLE
Security Vulnerabilities with the latest docker image

### ISSUE THREAD

**Issue by Yogesh-BK** [pact-foundation/pact_broker-client#125]
While scanning with latest docker image for vulnerabilities with the below command,
trivy image pactfoundation/pact-cli:latest
Many vulnerabilities(including high and Critical) are there as below

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/92719848/215715283-c811c9b5-0574-42e0-80e6-ce762cb934b8.png">

<img width="1790" alt="image" src="https://user-images.githubusercontent.com/92719848/215715371-a3303957-80cf-4612-a3b6-67165ae00035.png">

Expected behaviour
A image which has no vulnerabilities

**Comment by bethesque** [comment]
New image is out with upgraded base image.
