### ISSUE TITLE
Spec `v3` Pact files cannot be merged when publishing

### ISSUE THREAD

**Issue by martinslota** [pact-foundation/pact_broker-client#131]
### Software versions

- **OS**: Mac OS 13.2.1
- **Consumer Pact library**:  PactJS v 11.0.2
- **Provider Pact library**: N/A
- **Node Version**: v18.15.0

### Issue Checklist

Please confirm the following:

- [X] I have upgraded to the latest
- [X] I have the read the FAQs in the Readme
- [X] I have triple checked, that there are **no unhandled promises** in my code
- [X] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [X] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

Several `v3` Pact files can be merged and published using the `Publisher`.

### Actual behaviour

Merging fails because the merger seems to assume to be merging spec `v2` Pact files.

### Steps to reproduce

See https://github.com/martinslota/pact-js-bug-cannot-merge-v3-pacts.

### Relevant log files

[failure.log](https://github.com/pact-foundation/pact-js-core/files/11094112/failure.log)

**Comment by mefellows** [comment]
I've moved the issue to the upstream source of the problem.

**Comment by bethesque** [comment]
Sorry, I know this is super old, but yes, you should be able to merge multiple files for the same consumer and provider before publishing, and it should work for v3. Can you provide a couple of sample files for me @martinslota

**Comment by martinslota** [comment]
Hi @bethesque!

I just re-ran `npm ci && npm test` in https://github.com/martinslota/pact-js-bug-cannot-merge-v3-pacts and got these files:

* [pacts1/MyConsumer-MyProvider.json](https://github.com/pact-foundation/pact_broker-client/files/12897223/MyConsumer-MyProvider.json)
* [pacts2/MyConsumer-MyProvider.json](https://github.com/pact-foundation/pact_broker-client/files/12897227/MyConsumer-MyProvider.json)

The error logged out looked like this:

```
[20:10:47.021] INFO (95049): pact-core@13.13.6: Publishing pacts to broker at: http://localhost:9292
[20:10:54.859] WARN (95049): pact-core@13.13.6: Pact exited with code 1.
[20:10:54.861] ERROR (95049): pact-core@13.13.6: Pact publication failed with non-zero exit code. Full output was:
Merging /Users/msl/code/pact-js-bug-cannot-merge-v3-pacts/pacts1/MyConsumer-MyProvider.json, /Users/msl/code/pact-js-bug-cannot-merge-v3-pacts/pacts2/MyConsumer-MyProvider.json

PactBroker::Client::PactMergeError - Two interactions have been found with same description ("request") and provider state (nil) but a different request or response. Please use a different description or provider state, or hard-code any random data.

{"description":"request","providerStates":[{"name":"state 1"}],"request":{"method":"GET","path":"/1"},"response":{"status":200}}

{"description":"request","providerStates":[{"name":"state 2"}],"request":{"method":"GET","path":"/2"},"response":{"status":200}}

/Users/msl/code/pact-js-bug-cannot-merge-v3-pacts/node_modules/@pact-foundation/pact-core/src/publisher.js:111
                    return reject(new Error(message));
                                  ^

Error: Pact publication failed with non-zero exit code. Full output was:
Merging /Users/msl/code/pact-js-bug-cannot-merge-v3-pacts/pacts1/MyConsumer-MyProvider.json, /Users/msl/code/pact-js-bug-cannot-merge-v3-pacts/pacts2/MyConsumer-MyProvider.json

PactBroker::Client::PactMergeError - Two interactions have been found with same description ("request") and provider state (nil) but a different request or response. Please use a different description or provider state, or hard-code any random data.

{"description":"request","providerStates":[{"name":"state 1"}],"request":{"method":"GET","path":"/1"},"response":{"status":200}}

{"description":"request","providerStates":[{"name":"state 2"}],"request":{"method":"GET","path":"/2"},"response":{"status":200}}

    at ChildProcess.<anonymous> (/Users/msl/code/pact-js-bug-cannot-merge-v3-pacts/node_modules/@pact-foundation/pact-core/src/publisher.js:111:35)
    at Object.onceWrapper (node:events:629:26)
    at ChildProcess.emit (node:events:526:35)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)

Node.js v18.17.0
```
