### ISSUE TITLE
`--ignore` parameter order matters

### ISSUE THREAD

**Issue by dimkin-eu** [pact-foundation/pact_broker-client#171]
I discovered by accident that the order of the parameters is crucial; otherwise, it can lead to unexpected errors.

```
docker run --rm -it pactfoundation/pact-cli:latest /bin/sh   
# pact-broker version
1.76.0
```

```
~ #  pact-broker can-i-deploy --pacticipant someName --ignore someOtherName --version 9ec0ec93 --to-environment uat --broker-base-url URL --broker-username user --broker-password pass 

The version must be specified using `--version VERSION`, `--branch BRANCH` `--latest`, `--latest TAG`, or `--all TAG` for pacticipant someName
```

``` 
~ #  pact-broker can-i-deploy --pacticipant someName --version 9ec0ec93 --ignore someOtherName --to-environment uat --broker-base-url URL --broker-username  user --broker-password pass 
Computer says yes \o/ 
```

There is nothing about it in [docs](https://docs.pact.io/pact_broker/client_cli/readme)

Still there are some [CLI guidelines ](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html)
```
Guideline 11:
The order of different options relative to one another should not matter, 
unless the options are documented as mutually-exclusive 
and such an option is documented to override any incompatible options preceding it...
```

**Comment by mefellows** [comment]
<img width="1475" alt="Screenshot 2024-09-05 at 6 22 16 PM" src="https://github.com/user-attachments/assets/ae8b5afb-52e7-4329-a777-9e99c6c8c7d5">

Well, it does say this

**Comment by dimkin-eu** [comment]
oh mama, then closing as `user error` ? :)
![image](https://github.com/user-attachments/assets/eff29d4b-ccc4-4452-8a49-215648bc0454)

**Comment by mefellows** [comment]
I think so. If there are other strange variants, you might consider re-opening. Thor (the underlying CLI library) does have [its quirks](https://mattbrictson.com/blog/fixing-thor-cli-behavior), but changing the behaviour would result in a breaking change of sorts, so we'd possibly need to consider a major version bump just to straighten it out!
