### ISSUE TITLE
Dynamically retrieve pacts for a given provider

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact_broker-client#24]
@uglyog can you tell me what you've done in the JVM in terms of the tags?

**Comment by uglyog** [comment]
It can either retrieve all pacts with a set of tags, or latest.

**Comment by bethesque** [comment]
The set of tags is OR'd?

**Comment by uglyog** [comment]
Effectively, it fetches the pacts for each tag and adds them to the list to be verified.

**Comment by bethesque** [comment]
And if a pact does not exist for the given tag, it just continues without error?

**Comment by uglyog** [comment]
It fails gracefully on each call, but will fail if there is not at least one pact (unless overridden with a flag).

**Comment by bethesque** [comment]
At least one pact per consumer/provider, or at least one pact overall?

**Comment by uglyog** [comment]
One consumer with a pact.

**Comment by bethesque** [comment]
Are you using the `pb:latest-provider-pacts` and `pb:latest-provider-pacts-with-tag` relations?

**Comment by uglyog** [comment]
Yes

**Comment by yuranos** [comment]
Hi,
One related question. So, the provider is only verified against the latest version on pact based on:
https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-pact-broker/src/main/groovy/au/com/dius/pact/provider/broker/PactBrokerClient.groovy#L62

Isn't it at odds with:
https://docs.pact.io/documentation/versioning_in_the_pact_broker.html

Wouldn't it be reasonable to verify a provider against all versions? Or at least have such an option. In big companies/teams APIs/Services normally have more than 1 version and all of them are quite critical.

**Comment by yuranos** [comment]
@uglyog, I can try to add this feature, if you are fine with my reasoning.

**Comment by bethesque** [comment]
@yuranos, thanks for offering, but someone is working on this code at the moment. And yes, we'll be adding the "verify all prod pacts" option as well as the latest. As you say, it is a common use case.

**Comment by bethesque** [comment]
@yuranos if you want to add it to the JVM implementations, you'll just need to wait for me to release the new "all pacts tagged X" endpoint in the broker. It should be out soon.

**Comment by yuranos** [comment]
Sounds good, @bethesque . Let me know what ticket/channel or whatever else I need to follow so as not to miss it.

**Comment by bethesque** [comment]
I've just released 2.19.0. You'll find a `pb:provider-pacts-with-tag` relation in the index now that will return _all_ the pacts that have a version with the specified tag, not just the latest ones.

**Comment by bethesque** [comment]
Notes for self: `--consumer foo --tag branch-name --all --fallback master --required `

**Comment by bethesque** [comment]
So done.
