### ISSUE TITLE
Dependency on rake

### ISSUE THREAD

**Issue by nicpillinger** [pact-foundation/pact_broker-client#32]
hi @bethesque so I'll try opening this in the right place now! If you create a Gemfile with just your gem in it eg.
https://gist.github.com/nicpillinger/4de98867b8ad8e1946975dff879f166a

on trying to execute the pact-broker you get this:
https://www.dropbox.com/s/7sf6y21x6f3bc9k/Screenshot%202018-05-29%2010.18.50.png?dl=0

adding rake back into the Gemfile fixes it
https://www.dropbox.com/s/yvorkxps702eltc/Screenshot%202018-05-29%2010.20.56.png?dl=0

this is on OSX, no docker involvement at all. I'm using RVM and ruby 2.4.4

**Comment by bethesque** [comment]
Finally recreated it! Can fix now.

**Comment by bethesque** [comment]
I've released 1.47.1 of the standalone, and 1.15.1 of the pact_broker-client.

**Comment by bethesque** [comment]
Is there a wrapper implementation that you need updated @nicpillinger?
