### ISSUE TITLE
Handle running provider tests from webhook againts contract with specific tag and version

### ISSUE THREAD

**Issue by MaciekBBB** [pact-foundation/pact_broker-client#37]
Hi,

I have a problem with running a webhook that should trigger provider tests for specific non prod contract. The webhook is defined as:

{
      "events": [{
        "name": "contract_content_changed"
      }],
      "request": {
        "method": "POST",
        "url": "xyz",
         "body": {
      "thisPactWasPublished" : "${pactbroker.pactUrl}"
    }
      }
    }

and in the log I can see that it was properly run however it triggers tests for prod tag (not the one that was just published). For the provider I have defined:

@PactBroker(host = "xyz", port = "80", tags = "prod"), because I want to run provider tests against prod contract within their normal pipeline (not triggered).

Is there an option to trigger a webhook to run provider tests against specific tagged contract (not the prod one that is hardcoded in the setup)?

**Comment by bethesque** [comment]
There is a template variable for the consumer version tags that could be used to pass through the tag name as an environment variable (or some other method) to your provider verification. You may want to use an intermediate build to do any logic required.

**Comment by MaciekBBB** [comment]
Thanks for the information.
