### ISSUE TITLE
How to trigger provider tests if contract has not been changed but provider changed their contract tests to start passing verification

### ISSUE THREAD

**Issue by basiaBB** [pact-foundation/pact_broker-client#38]
Hi,

I have a problem with webhook to trigger provider contract tests when contract has not been changed but provider tests have been.

For consumer I developed new contract on branch with specific version and tag name. Then published it, triggered webhook to run provider tests for this contract. Provider was not ready so the verification failed.

After it provider added new contract tests at his site and released it.

Now, as a consumer I have a problem to pass can-i-deploy step because in my pipeline I am:
- running contract tests - it passed
- publishing contract - it passed however it will not trigger provider pipeline because contract has not been changed.

As a result I still see that can-i-deploy returns false.

How can I solve this problem?

**Comment by anto-ac** [comment]
The provider will have to run its pipeline/build (that includes the provider tests) once they've made the changes to the application code and/or the provider tests.

Normally, once these changes are pushed remotely, you would have a CI build been automatically triggered.

You would have to wait until the provider verification succeeds before you can get a true result from can-i-deploy.

**Comment by bethesque** [comment]
Exactly ^^ The provider should include the verification tests as part of its own CI, and hence will publish a new verification result when the commit is pushed. If you would like more visibility on when a contract has passed, you could use webhooks to send commit statuses to your repository or to your team chat. Have a look at the webhook template page on the Pact Broker wiki.

Closing this, as it has been answered, but feel free to open it again if you need more information.
