### ISSUE TITLE
can-i-deploy does not retry in case of connection errors

### ISSUE THREAD

**Issue by tinexw** [pact-foundation/pact_broker-client#40]
The `retry-while-unknown` and `retry-interval` parameters don't work as expected if the CLI cannot connect to the broker:

Expected behavior when passing `--retry-while-unknown=5 --retry-interval=60`: 5 attempts are made, wait time between tries is 60 seconds.

Actual behavior: 3 attempts are made, wait time between tries is 3(?) seconds (less than 60 in any case).

```
Kristines-MBP:bin tine$ time ./pact-broker can-i-deploy --retry-while-unknown=5 --retry-interval=60  -a messaging-app -b http://broker_app -e feaba6227a48e03c0eeb1c4a27d685496349e78d
Error making request - [...], attempt 1 of 3
Error making request - [...], attempt 2 of 3
Error making request - [...], attempt 3 of 3
Error retrieving matrix. SocketError - getaddrinfo: nodename nor servname provided, or not known
[...]

real    0m10.391s
user    0m0.301s
sys     0m0.060s
```

Not sure though if this case should actually be covered by the retry logic. Feel free to close if it shoudn't.

**Comment by bethesque** [comment]
What version of the client are you using?

**Comment by bethesque** [comment]
Ah - the retry-while-unknown only applies when there is a response returned and one of the results is unknown. In the normal "there was an error connecting" scenario, it just does a default retry sequence, that you can see in the logs there.

**Comment by bethesque** [comment]
We could add a `--retry-while-error=X` - however, if your broker host name is not available for 3x5seconds as it seems not to be, I'd suggest that there are bigger problems, and waiting longer may not be the solution.

**Comment by tinexw** [comment]
It's fine. I think I got confused because I initially used 3 for number of retries and thought that `attempt n of 3` was related to this 3.
