### ISSUE TITLE
describe-version cuts off version

### ISSUE THREAD

**Issue by tinexw** [pact-foundation/pact_broker-client#42]
When I run the following command

```
./pact/bin/pact-broker describe-version -a user-service -b http://localhost -l prod 
```

I get the following output: 
```
NUMBER                         | TAGS
-------------------------------|-----
a83153b34648b4a7fb17700ff09... | prod
```

The actual version is `a83153b34648b4a7fb17700ff09519f893c520a7`. Is there an option to print the whole version in the table without the ellipsis?

**Comment by bethesque** [comment]
Use the json output.

**Comment by tinexw** [comment]
Yeah, I'm already using the json output because of it. I would just prefer to use the table output because I can more easily grep/cut the version number from it and don't need something like jq to parse the JSON.
