### ISSUE TITLE
Pact-Provider-Verifier Errors When Consumer-Version-Tag Contains Slashes

### ISSUE THREAD

**Issue by sthomas1978** [pact-foundation/pact_broker-client#44]
Hi

When I try to run the the pact-provider-verifier when the --consumer-version-tag contains "/" it errors. I have tried wrapping the tag in quotes but it still errors

i.e

`pact-provider-verifier --pact-broker-base-url http://localhost:1234 --provider-base-url http://localhost:1111 --provider-states-setup-url http://localhost:1111/provider-states --consumer-version-tag "<TAG WITH / SLASH>" --provider "<PROVIDER>" -v`

Here is the output of the error I receive

`C:/Program Files (x86)/pact-1.61.0-win32/pact/lib/vendor/ruby/2.2.0/gems/pact-1.36.0/lib/pact/pact_broker/fetch_pacts.rb:84:in 'pact_urls': undefined method 'collect' for nil:NilClass (NoMethodErr
)
        from C:/Program Files (x86)/pact-1.61.0-win32/pact/lib/vendor/ruby/2.2.0/gems/pact-1.36.0/lib/pact/pact_broker/fetch_pacts.rb:58:in 'block in tagged_pacts_for_provider'
        from C:/Program Files (x86)/pact-1.61.0-win32/pact/lib/vendor/ruby/2.2.0/gems/pact-1.36.0/lib/pact/pact_broker/fetch_pacts.rb:56:in 'collect'
        from C:/Program Files (x86)/pact-1.61.0-win32/pact/lib/vendor/ruby/2.2.0/gems/pact-1.36.0/lib/pact/pact_broker/fetch_pacts.rb:56:in 'tagged_pacts_for_provider'
        from C:/Program Files (x86)/pact-1.61.0-win32/pact/lib/vendor/ruby/2.2.0/gems/pact-1.36.0/lib/pact/pact_broker/fetch_pacts.rb:40:in 'call'
        from C:/Program Files (x86)/pact-1.61.0-win32/pact/lib/vendor/ruby/2.2.0/gems/pact-1.36.0/lib/pact/pact_broker/fetch_pacts.rb:33:in 'call'
        from C:/Program Files (x86)/pact-1.61.0-win32/pact/lib/vendor/ruby/2.2.0/gems/pact-1.36.0/lib/pact/pact_broker.rb:12:in 'fetch_pact_uris'
        from C:/Program Files (x86)/pact-1.61.0-win32/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.20.0/lib/pact/provider_verifier/aggregate_pact_configs.rb:38:in 'non_pending_pact_uri
        from C:/Program Files (x86)/pact-1.61.0-win32/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.20.0/lib/pact/provider_verifier/aggregate_pact_configs.rb:31:in 'pacts_urls_from_brok
'
        from C:/Program Files (x86)/pact-1.61.0-win32/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.20.0/lib/pact/provider_verifier/aggregate_pact_configs.rb:21:in 'call'
        from C:/Program Files (x86)/pact-1.61.0-win32/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.20.0/lib/pact/provider_verifier/aggregate_pact_configs.rb:9:in 'call'
        from C:/Program Files (x86)/pact-1.61.0-win32/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.20.0/lib/pact/provider_verifier/app.rb:168:in 'all_pact_urls'
        from C:/Program Files (x86)/pact-1.61.0-win32/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.20.0/lib/pact/provider_verifier/app.rb:32:in 'call'
        from C:/Program Files (x86)/pact-1.61.0-win32/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.20.0/lib/pact/provider_verifier/app.rb:26:in 'call'
        from C:/Program Files (x86)/pact-1.61.0-win32/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.20.0/lib/pact/provider_verifier/cli/verify.rb:36:in 'verify'
        from C:/Program Files (x86)/pact-1.61.0-win32/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.0/lib/thor/command.rb:27:in 'run'
        from C:/Program Files (x86)/pact-1.61.0-win32/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in 'invoke_command'
        from C:/Program Files (x86)/pact-1.61.0-win32/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.0/lib/thor.rb:387:in 'dispatch'
        from C:/Program Files (x86)/pact-1.61.0-win32/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.0/lib/thor/base.rb:466:in 'start'
        from C:/Program Files (x86)/pact-1.61.0-win32/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.20.0/lib/pact/provider_verifier/cli/custom_thor.rb:17:in 'start'
        from C:/Program Files (x86)/pact-1.61.0-win32/pact/lib/app/pact-provider-verifier.rb:33:in '<main>'`

**Comment by sthomas1978** [comment]
@bethesque - Hi Beth, have you had a chance to reproduce the issue yet?

Thanks

Simon

**Comment by bethesque** [comment]
I've fixed this in version 1.17.0

**Comment by sthomas1978** [comment]
@bethesque - Download latest version of pact-ruby-standalone version pact-1.63.0 and it seems to have resolved the issue. Thankyou
