### ISSUE TITLE
pact-broker create-webhook fails to authenticate

### ISSUE THREAD

**Issue by rafaroca** [pact-foundation/pact_broker-client#50]
Hi,
first of all thanks for the great work on pact in general!

I am trying to create a webhook using the CLI, but I fail to authenticate. The following command always returns 401

```sh
$ ./node_modules/.bin/pact-broker create-webhook 'https://gitlab.com/api/v4/projects/XXX/ref/master/trigger/pipeline?token=XXX&variables[PACT_CONSUMER_TAG]=feature123' -X POST --provider order-service --consumer backoffice-view --broker-base-url https://XXX.pact.dius.com.au --broker-token XXX --contract-content-changed
Error creating webhook. response status=401 body=
```

edit:
I have this in my `package.json`:
```
"devDependencies": {
    "@pact-foundation/pact-node": "^8.4.0",
    "@pact-foundation/pact": "^8.2.3"
}
```

**Comment by bethesque** [comment]
Already fixed in https://github.com/pact-foundation/pact_broker-client/commit/9d3170ef7f76a65d071fd2beb9ee87ee6f909153

Please raise an issue to have the standalone version updated in pact-node.

**Comment by rafaroca** [comment]
Thanks for the fix. I created https://github.com/pact-foundation/pact-node/issues/165
