### ISSUE TITLE
can-i-deploy fails if there are > 100 applicable verifications

### ISSUE THREAD

**Issue by kuangp** [pact-foundation/pact_broker-client#53]
Hi,

I am currently running into a situation where can-i-deploy is giving the following example result:
` ./pact-broker can-i-deploy  --pacticipant foo --broker-base-url https://pact.broker.com/ --version abc123 --to staging`

`Computer says no ¯\_(ツ)_/¯`

CONSUMER          | C.VERSION                      | PROVIDER         | P.VERSION                      | SUCCESS?
------------------|--------------------------------|------------------|--------------------------------|---------
foo | abc123 | test-provider           | efg456                       | true
foo | abc123 | test-provider2 | hijk123 | true

`There is no verified pact between version abc123 of foo and the latest version of bar with tag staging (xyz123)`

However there is clearly a verification for foo -> bar when I check the broker.
Upon debugging further I believe the can-i-deploy script is making the following request:
`https://pact.broker.com/matrix?q%5B%5Dpacticipant=foo&q%5B%5Dversion=abc123&tag=staging&latest=true&latestby=cvp`
The response from the above request matches the result of can-i-deploy but when I add an additional query (`@limit=500`), the request will return the correct response which includes the verification for foo -> bar.

My assumption is that the default limit of 100 verifications is not including enough results to correctly evaluate can-i-deploy from a broker with high usage. I think can-i-deploy needs to be refactored to include all results so it can fully evaluate a correct response?

**Comment by bethesque** [comment]
@kuangp I understand the issue. I'll see if I can prioritise getting this fixed for you. In the meantime. Can you try deleting your old data? Here's a script that might help https://github.com/pact-foundation/pact_broker/blob/master/script/prod/clean-up.sql

**Comment by bethesque** [comment]
Another quick fix for you - I've added a --limit option to can-i-deploy so you can manually set it while I get the bug fixed (unfortunately, it's going to take a bit of work). What packaging of can-i-deploy are you using?

**Comment by bethesque** [comment]
I've put out a new release with the --limit. It won't show up in the help page, as it shouldn't need to be used once I've fixed the backend.

**Comment by bethesque** [comment]
Please upgrade to the latest pact broker.
