### ISSUE TITLE
What is pact-broker url?

### ISSUE THREAD

**Issue by Yamuna-Rani** [pact-foundation/pact_broker-client#59]
How to create the pact-broker url?

**Comment by bethesque** [comment]
I don't know what you are talking about, I'm sorry. Can you please give an example.

**Comment by rbhati** [comment]
`http://localhost/` -  deployed local at default port - 80
`http://localhost:1234/` - deployed local at port 1234
`http://myserver.domain.com/` - deployed at myserver over domain with port - 80
`http://myserver.domain.com:443/ or https://myserver.domain.com`  - deployed on myserver over domain with SSL .....
hope this helps

**Comment by bethesque** [comment]
I don't know where you've installed your Pact Broker from, or where you've deployed it to, so I can't help you! Are you using docker/docker-compose? Are you using the Ruby gem? Are you using pactflow.io? Did you deploy it yourself, or did someone else deploy it? If someone else deployed it, I suggest you ask them.

**Comment by mefellows** [comment]
@rbhati are you asking how to deploy a pact broker so you can configure the pact broker client to talk to it? Perhaps it would be helpful for you to explain what you're trying to do.

See the [XY problem](https://mywiki.wooledge.org/XyProblem) for helping us help you.

**Comment by Yamuna-Rani** [comment]
I have downloaded this zip file(pact-1.72.2-win32.zip)  from https://github.com/pact-foundation/pact-ruby-standalone/release and extracted.

After that I run this command
$ cd pact/bin
$ ./pact-mock-service --help start
$ ./pact-provider-verifier --help verify

What I need to do next?

**Comment by bethesque** [comment]
You need to read a lot of documentation! 

https://docs.pact.io/
https://docs.pact.io/5-minute-getting-started-guide
https://docs.pact.io/getting_started/sharing_pacts

for starters. The Pact Broker is a service for sharing contracts ("pacts") and it's a service that you either need need to deploy yourself, or use pactflow.io https://github.com/pact-foundation/pact_broker#usage

**Comment by mefellows** [comment]
Have you already written pact tests? I suppose, what led you to downloading the client in the first place and What are you trying to achieve?

**Comment by rbhati** [comment]
> @rbhati are you asking how to deploy a pact broker so you can configure the pact broker client to talk to it? Perhaps it would be helpful for you to explain what you're trying to do.
> 
> See the [XY problem](https://mywiki.wooledge.org/XyProblem) for helping us help you.

@mefellows I was trying to help @Yamuna-Rani, because I have learned a lot about pact in past few weeks

**Comment by rbhati** [comment]
> I have downloaded this zip file(pact-1.72.2-win32.zip) from https://github.com/pact-foundation/pact-ruby-standalone/release and extracted.
> 
> After that I run this command
> $ cd pact/bin
> $ ./pact-mock-service --help start
> $ ./pact-provider-verifier --help verify
> 
> What I need to do next?

@Yamuna-Rani best way to setup pact-broker is via docker -> https://github.com/pact-foundation/pact-broker-docker
follow the readme and use
`docker-compose -f docker-compose.yml up`

**Comment by mefellows** [comment]
We appreciate and thank you for helping @rbhati. You might understand the confusion from a maintainers point of view however, because the dialogue that we see (i.e. what is here) makes absolutely no sense to us and what @Yamuna-Rani is trying to achieve. 

If it's about this tool, then please articulate the issue. If it's about running a Pact Broker and the documentation isn't clear, then raise an issue over there.

A great place to really get started, is heading to pact.io and chatting with the community at slack.pact.io - that is the place for questions and conversation.
