### ISSUE TITLE
Publish pact files with tags

### ISSUE THREAD

**Issue by itsDanOades** [pact-foundation/pact_broker-client#6]
Hi,

I see some support in the pact broker client for reading pacts with tags, is there a task/option to publish tags to the broker?

**Comment by bethesque** [comment]
Not yet, but it should be pretty easy to add it in. Happy to accept PRs.

**Comment by bethesque** [comment]
It would need an extra `tag` or `tags` property here: https://github.com/bethesque/pact_broker-client/blob/master/lib/pact_broker/client/tasks/publication_task.rb and either pass in the tag, or have another TagPacts operation.

**Comment by itsDanOades** [comment]
Thanks, I'm going down the separate rake task route. Will submit  a PR when ready.

**Comment by correctclick** [comment]
do we have a similar publishing mechanism for JVM (JUnit)?

**Comment by bethesque** [comment]
@uglyog will know.

**Comment by uglyog** [comment]
Publishing task in the JVM does not support tags

**Comment by correctclick** [comment]
Thank you very much for quick response. I do see that PACT verification in JVM supports tag. Could you please let me know if there is any future plans to support it or any suggestion to develop it on our own?

**Comment by bethesque** [comment]
Sorry @correctclick, I don't understand your question. @uglyog says that tags are not supported, but you say that it does?

**Comment by uglyog** [comment]
Tags are supported for fetching pacts from the broker. The publish task does not support publishing a pact with a tag.

**Comment by bethesque** [comment]
Ahh!!

**Comment by suresh2000** [comment]
@uglyog  -  Do you have any plan to include TAG in the Publishing task in the JVM ?

**Comment by uglyog** [comment]
There are a long list of outstanding items to work on, so I can't really say.

**Comment by bethesque** [comment]
This has been done for ages. Closing.
