### ISSUE TITLE
Verify for basic auth

### ISSUE THREAD

**Issue by Sridhar1974** [pact-foundation/pact_broker-client#70]
what is the command to verify basic auth (username and password)

for ex this is for token how can get the same for basic auth 

mvn clean install -Dpactbroker.host=<Brokerhost> -Dpactbroker.protocol=<broker_protocol> -Dpactbroker.auth.scheme=bearer -Dpactbroker.auth.username=<Token>

**Comment by mefellows** [comment]
This is a JVM specific question.

I think, however, that you want `pactbroker.auth.username` and `pactbroker.auth.password`.

see https://github.com/DiUS/pact-jvm/blob/5b6d9a6747ed36bf6b5e1dcb9518ca9a06507151/provider/junit/README.md#more-java-system-properties

**Comment by Sridhar1974** [comment]
I am using the below command 

mvn clean install -Dpactbroker.host=dev.pact.cerebro.ing.net -Dpactbroker.protocol=https -Dpactbroker.auth.scheme=username -Dpactbroker.auth.username=test


While I run my test is passed but not verified in Pact broker 


Test set: com.test.product1.Product1BrokerTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.053 s <<< FAILURE! - in com.test.product1.Product1BrokerTest
initializationError  Time elapsed: 0.039 s  <<< ERROR!
au.com.dius.pact.pactbroker.RequestFailedException: Request to path '/' failed with response 'HTTP/1.1 401 Unauthorized'

**Comment by bethesque** [comment]
Have you set the `-Dpactbroker.auth.password` property? 401 means your credentials are wrong or missing.
