### ISSUE TITLE
Not able to verify pacts in pact broker 

### ISSUE THREAD

**Issue by Sridhar1974** [pact-foundation/pact_broker-client#71]
Hi

We are using old pact broker let me know for any issues however my test are passing also in pact folder

cmd line  used : 
 mvn clean install -Dpactbroker.host=dev.pact.cerebro.ing.net -Dpactbroker.protocol=https -Dpactbroker.auth.scheme=username -Dpactbroker.auth.scheme=password -Dpactbroker.auth.username= -Dpactbroker.auth.password=

error log 

[ERROR] Errors: 
[ERROR]   Product1BrokerTest » RequestFailed Request to path '/' failed with response 'H...
[INFO]
[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  37.530 s
[INFO] Finished at: 2020-05-26T15:15:20+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project provider1: There are test fa
ilures.
[ERROR]
[ERROR] Please refer to C:\Sridhar\Repository\pact-demo\provider1\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:

please help

**Comment by bethesque** [comment]
I'm sorry, there's nothing there that can help me identify the issue.

The rest of the text after `[ERROR] Product1BrokerTest » RequestFailed Request to path '/' failed with response 'H...` might help. 

I'm afraid I'm not a JVM developer, so I don't know how, but I know that you can turn on debug logging for pact jvm. 

This is not an issue with the Pact Broker. It is an issue with your configuration of Pact-JVM. Please look for help in a more appropriate channel (eg the #pact-jvm-help channel of the Pact Slack workspace).

**Comment by bethesque** [comment]
By the way, this repository is for the Ruby client of the Pact Broker - nothing to do with the JVM.

**Comment by bethesque** [comment]
Why have you got this twice? `-Dpactbroker.auth.scheme=username -Dpactbroker.auth.scheme=password`. I don't know how pact-jvm works, but this seems wrong. Pretty sure there should only be one of these. A quick search of github code seems to suggest that there should be one, and it should be "Basic".

https://github.com/search?q=%22pactbroker.auth.scheme%22&type=Code
