### ISSUE TITLE
can-i-deploy : can not specify tag that should exist before deploying specific version

### ISSUE THREAD

**Issue by arshadalis** [pact-foundation/pact_broker-client#74]
I want to specify a tag that should exist before I deploy a version with the new tag.
For example for service **Foo**  I am deploying a tag **Prod** with version 1.0.0,
but before that I want to be sure that tag **Stage** exists.

We can do this for latest version using below command
pact-broker can-i-deploy --pacticipant Foo --latest Stage  --to Prod ...

in above case it will check for the latest version of Foo.
we cannot specify specific version and a tag to exist.

I want to do something like 
pact-broker can-i-deploy --pacticipant Foo --version 1.0.0 --ensure-tag Stage  --to Prod ...

any solutions ?? 
Thanks in advance.

**Comment by bethesque** [comment]
What behaviour do you want if the tag does not exist? Do you want it to be created, or do you want the command to fail?

If you want the tag to be created if it does not already exist, then use the CLI to create the tag before you run the can-i-deploy command.

```
pact-broker create-version-tag --pacticipant ${application} --version ${version} --tag ${stage}
```

If you want to stop the build if the tag does not exist on the version, then check if the tag exists before you call can-i-deploy like so.

```
existing_tags=$(pact-broker describe-version --pacticipant ${application} --version ${version} --output json | jq "[._embedded.tags[].name]" | jq 'join("\n")' --raw-output)
if [ $(echo "${existing_tags}" | grep "${stage}") ]; then
  echo "Version ${version} of ${application} has tag ${stage}"
  echo "Do can-i-deploy here"
else
  echo "Version ${version} of ${application} does not have tag ${stage}, aborting."
  exit 1
fi
```

You can see an example of these commands in this script https://github.com/pact-foundation/pact_broker-client/blob/master/example/scripts/deploy-consumer.sh

**Comment by arshadalis** [comment]
Great. This is exactly what I wanted to do.
Thank you So much.
