### ISSUE TITLE
Pactbroker cli on windows from local machine throws ssl error

### ISSUE THREAD

**Issue by pavankumar1986** [pact-foundation/pact_broker-client#83]
I am using https://github.com/pact-foundation/pact-ruby-standalone/releases (1.88.11-win32) on my windows machine. I have set the env variable for ssl_cert_dir but still facing below issue. I have tried setting ssl_cert_file.

Error making request - OpenSSL::SSL::SSLError SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate) /usr/lib/ruby/gems/2.5.0/gems/pact_broker-client-1.20.0/lib/pact_broker/client/matrix.rb:13:in get', attempt 1 of 3`

**Comment by pavankumar1986** [comment]
> I've put out a new release. Upgrade and set `PACT_BROKER_DISABLE_SSL_VERIFICATION=true`.

Using the latest (https://github.com/pact-foundation/pact-ruby-standalone/releases/tag/v1.88.46) along with windows environment variable PACT_BROKER_DISABLE_SSL_VERIFICATION=true should be working right?

**Comment by bethesque** [comment]
Yes. Is it not?

**Comment by pavankumar1986** [comment]
Its still not working. Fails for same reason.
I downloaded the zip from https://github.com/pact-foundation/pact-ruby-standalone/releases/tag/v1.88.46
And set the windows environment variable PACT_BROKER_DISABLE_SSL_VERIFICATION=true
Then ran the pact-broker can-i-deploy -a consumername -k token -b pactflow url --latest

**Comment by pavankumar1986** [comment]
Beth, I think the issue is fixed in pact_broker-client git repository, but not on the pact-ruby-standalone. Any chance that this feature can be implemented in pact-ruby-cli.

**Comment by pavankumar1986** [comment]
Beth, Created PR for same changes on pact-ruby-standalone, please review.
https://github.com/pact-foundation/pact-ruby-standalone/pull/66/files

**Comment by bethesque** [comment]
Thanks. I've put out a release. Please test and let me know.
