### ISSUE TITLE
describe-version with a spaced pacticipant produces an error

### ISSUE THREAD

**Issue by Lyr-7D1h** [pact-foundation/pact_broker-client#84]
`pact-broker describe-version -a 'A Spaced Pacticipant' -b asdf.pactflow.io`
Produces
`bad URI(is not URI?): https://npa.pactflow.io/pacticipants/A Spaced Pacticipant/latest-version (URI::InvalidURIError)`

**Comment by bethesque** [comment]
What happens if you use double quotes?

**Comment by bethesque** [comment]
Update to the latest version please. I've put out a fix.
