### ISSUE TITLE
pact-broket can-i-deploy --ignore not working

### ISSUE THREAD

**Issue by gonultoktay** [pact-foundation/pact_broker-client#90]
I want to use the ignore command as I have shown in the example below. But B is still shown in the matrix and can-i-deploy fails. B is a third party software service, so there is currently no provider test.
How can ignore B in this case?

- pact-broker can-i-deploy
  --pacticipant A --latest
  --ignore B
  --to master
  --retry-while-unknown=12
  --retry-interval=10
  --verbose

CONSUMER | C.VERSION | PROVIDER   | P.VERSION | SUCCESS? | RESULT#
------------ |-------------|------------|-------------|------------|--------
A                   | bf87391c     | C                 | 2f304461     | true            | 1      
A                   | bf87391c     | B                 | ???                | ???              |        
VERIFICATION RESULTS
--------------------

{
  "summary": {
    "deployable": null,
    "reason": "There is no verified pact between the latest version of A (bf87391c) and the latest version of B with tag master (no such version exists)",
    "success": 1,
    "failed": 0,
    "unknown": 1
  },
  "matrix": [
    {
      "consumer": {
        "name": "A",
        "version": {
          "number": "bf87391c",
          "_links": {
            "self": {
              "href": "[MASKED]/pacticipants/A/versions/bf87391c"
            }
          }
        },
        "_links": {
          "self": {
            "href": "[MASKED]/pacticipants/A"
          }
        }
      },
      "provider": {
        "name": "C",
        "version": {
          "number": "2f304461"
        },
        "_links": {
          "self": {
            "href": "[MASKED]/pacticipants/C"
          }
        }
      },
      "pact": {
        "createdAt": "2021-08-03T16:23:41+00:00",
        "_links": {
          "self": {
            "href": "[MASKED]/pacts/provider/C/consumer/A/version/bf87391c"
          }
        }
      },
      "verificationResult": {
        "success": true,
        "verifiedAt": "2021-08-03T14:34:30+00:00",
        "_links": {
          "self": {
            "href": "[MASKED]/pacts/provider/C/consumer/A/pact-version/4779c60267be930fbacee9a1d2aa21f854c6a244/verification-results/3779"
          }
        }
      }
    },
    {
      "consumer": {
        "name": "A",
        "version": {
          "number": "bf87391c",
          "_links": {
            "self": {
              "href": "[MASKED]/pacticipants/A/versions/bf87391c"
            }
          }
        },
        "_links": {
          "self": {
            "href": "[MASKED]/pacticipants/A"
          }
        }
      },
      "provider": {
        "name": "B",
        "version": null,
        "_links": {
          "self": {
            "href": "[MASKED]/pacticipants/B"
          }
        }
      },
      "pact": {
        "createdAt": "2021-08-03T16:23:41+00:00",
        "_links": {
          "self": {
            "href": "[MASKED]/pacts/provider/B/consumer/A/version/bf87391c"
          }
        }
      },
      "verificationResult": null
    }
  ]
}

**Comment by bethesque** [comment]
I missed a line when I removed the feature flag. I've fixed that and put out a new release. Please upgrade to the latest version.
