### ISSUE TITLE
Broken link to `record-deployment`

### ISSUE THREAD

**Issue by TimothyJones** [pact-foundation/pact_broker-client#92]
Dmitry Munda [pointed out on slack](https://pact-foundation.slack.com/archives/CAN147DFD/p1628766181010500) that on this page:

https://docs.pact.io/pact_broker/client_cli/readme#deployments

There is this link:

https://docs.pact.io/record-deployment 

which is broken and should be:

https://docs.pact.io/pact_broker/recording_deployments_and_releases/

However, when opening the readme in this repo to fix it, I saw that it's inside the autogenerated docs section. I'm not sure how that works, so I'm opening an issue instead.

**Comment by bethesque** [comment]
Thanks. I needed to add the short link redirects to the netlify config https://github.com/pact-foundation/docs.pact.io/commit/a0782fea53f74ae1022919bcc50c159dcdf982c4

I do this so I can put short links in the output of the CLI tools.

**Comment by TimothyJones** [comment]
Oh man, that's awesome. I'm totally going to use this in pact-js.

**Comment by bethesque** [comment]
If it's something you want to print to the screen, put a "/go/" in the link, and then in the forwarding, put in the tracking information in the redirect URL. You'll see it in the netlify file. We're using this to work out if the links we put in the output are actually effective.
